# ! Docker-Compose Specification
version: "3.8"
# ? App Xentral
services:
  # Nginx Service
    webserver:
      image: nginx:alpine
      container_name: "${PROJECT_NAME}_webserver"
      tty: true
      ports:
        - "8080:80"
        - "443:443"
      volumes:
        - ./app-backend/:/var/www/app-backend
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      networks:
        - private

    # ? Bring up Mysql and configure the Database
    database:
      image: mysql:5.7
      container_name: "${PROJECT_NAME}_database"
      tty: true
      restart: 'always'
      expose: 
        - '3306'
      ports:
        - '3306:3306'
      environment:
        MYSQL_DATABASE: ${MYSQL_DB}
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_PASSWORD: ${PASS_ROOT_MYSQL}
        SERVICE_TAG: dev
        SERVICE_NAME: database
      volumes:
        - ./docker/mysqldb/dbdata/:/var/lib/mysql-files/
        - ./docker/mysqldb/my.cnf:/etc/mysqldb/my.cnf
      networks:
        - private
    # ? Build, Bring up Backend Container
    backend:
      build:
        context: .
        dockerfile: ./docker/backend/DockerFile
      container_name: "${PROJECT_NAME}_backend"
      tty: true
      environment:
          SERVICE_NAME: backend
      volumes:
        - ./app-backend/:/var/www/app-backend
        - ./docker/backend/supervisor/supervisord.conf:/etc/supervisord.conf
        - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      working_dir: /var/www/app-backend
      networks:
        - private
    # Frontend Service
    landlord:
      build:
        context: .
        dockerfile: ./docker/landlord/DockerFile
      container_name: "${PROJECT_NAME}_landlord"
      working_dir: /usr/src/app/app-frontend-landlord
      volumes: 
        - ./app-frontend-landlord/:/usr/src/app/app-frontend-landlord
      ports: 
        - '4000:4000' 
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4000"
      networks:
        - private
    tenant:
      build:
        context: .
        dockerfile: ./docker/tenant/DockerFile
      container_name: "${PROJECT_NAME}_tenant"
      working_dir: /usr/src/app/app-frontend-tenant
      volumes: 
        - ./app-frontend-tenant/:/usr/src/app/app-frontend-tenant
      ports: 
        - '4100:4100' 
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4100"
      networks:
        - private
# ! Define Project Network
networks:
    private:
        driver: bridge