version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: "app-backend"
        ports:
            - "8080:8000"
        command: bash -c 'php artisan serve --host 0.0.0.0'
        volumes:
            - ./:/var/www/html
    mariadb:
        image: mariadb:10.6
        restart: always
        volumes:
        - mariadb-data:/var/lib/mysql
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "40000:3306"   
volumes:
  mariadb-data:

